module.exports.descriptors = [
    'Forest',
    'Ancient',
    'Petrified',
    'Roaring',
    'Cascade',
    'Tumbling',
    'Silent',
    'Redwood',
    'Bullfrog',
    'Maple',
    'Misk',
    'Els',
    'Grizzly',
    'Ocean',
    'Sea',
    'Sky',
    'Dusky',
    'Diamond',
]
module.exports.places = [
    'Flats',
    'Village',
    'Canyon',
    'Pond',
    'Group Camp',
    'Horse Camp',
    'Ghost town',
    'Camp',
    'Dispersed Camp',
    'BlackCountry',
    'River',
    'Creek',
    'CreekSide',
    'Bay',
    'Spring',
    'Bayshores',
    'Sands',
    'Mule Camp',
    'Hunting Camp',
    'Cliffs',
    'Hollow',
]